# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui',
# licensing of 'view.ui' applies.
#
# Created: Sat May 18 20:39:49 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(430, 390)
        MainWindow.setMinimumSize(QtCore.QSize(430, 390))
        MainWindow.setMaximumSize(QtCore.QSize(430, 390))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/control parental.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_agregar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_agregar.setGeometry(QtCore.QRect(10, 10, 61, 61))
        self.btn_agregar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/plus-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_agregar.setIcon(icon1)
        self.btn_agregar.setIconSize(QtCore.QSize(32, 32))
        self.btn_agregar.setObjectName("btn_agregar")
        self.btn_quitar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quitar.setGeometry(QtCore.QRect(80, 10, 61, 61))
        self.btn_quitar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/minus-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_quitar.setIcon(icon2)
        self.btn_quitar.setIconSize(QtCore.QSize(32, 32))
        self.btn_quitar.setObjectName("btn_quitar")
        self.btn_importar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_importar.setGeometry(QtCore.QRect(220, 10, 61, 61))
        self.btn_importar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/sunset.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_importar.setIcon(icon3)
        self.btn_importar.setIconSize(QtCore.QSize(32, 32))
        self.btn_importar.setObjectName("btn_importar")
        self.btn_exportar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exportar.setGeometry(QtCore.QRect(290, 10, 61, 61))
        self.btn_exportar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/sunrise.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_exportar.setIcon(icon4)
        self.btn_exportar.setIconSize(QtCore.QSize(32, 32))
        self.btn_exportar.setObjectName("btn_exportar")
        self.btn_acerca = QtWidgets.QPushButton(self.centralwidget)
        self.btn_acerca.setGeometry(QtCore.QRect(360, 10, 61, 61))
        self.btn_acerca.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_acerca.setIcon(icon5)
        self.btn_acerca.setIconSize(QtCore.QSize(32, 32))
        self.btn_acerca.setObjectName("btn_acerca")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 80, 411, 271))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.btn_guardar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_guardar.setGeometry(QtCore.QRect(150, 10, 61, 61))
        self.btn_guardar.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_guardar.setIcon(icon6)
        self.btn_guardar.setIconSize(QtCore.QSize(32, 32))
        self.btn_guardar.setObjectName("btn_guardar")
        self.lbl_estado = QtWidgets.QLabel(self.centralwidget)
        self.lbl_estado.setGeometry(QtCore.QRect(10, 356, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_estado.setFont(font)
        self.lbl_estado.setText("")
        self.lbl_estado.setObjectName("lbl_estado")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "LaboonAccess", None, -1))
        self.btn_agregar.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Agregar Dominio", None, -1))
        self.btn_quitar.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Quitar Dominio", None, -1))
        self.btn_importar.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Importar Dominios", None, -1))
        self.btn_exportar.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Exportar Dominios", None, -1))
        self.btn_acerca.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Acerca De", None, -1))
        self.tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Dominios", None, -1))
        self.btn_guardar.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Guardar dominios", None, -1))

